import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";
import { ThemeProvider } from "./theme-provider";

export const metadata: Metadata = {
    title: "Create Next",
    description: "Generated by create next app",
    icons: {
        icon: "/assets/images/Logo.png",
    },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body cz-shortcut-listen="true">
                <StoreProvider>
                    <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
                        {children}
                        <ToastContainer />
                    </ThemeProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
